### ISSUE TITLE
AccessDenied - Missing required MWSAuthToken for Seller.

### ISSUE THREAD

**Issue by mirkos93** [looxis/laravel-amazon-mws#13]
- Laravel Amazon MWS Version: 0.1.9
- PHP Version: 7.4

### Description:
Has on the subject, Amazon requires me the MWSAuthToken, but i don't know how to set it on that package

### Steps To Reproduce:

```
AmazonMWS::feeds()
->setType($feedType) //_POST_PRODUCT_DATA_ 
->setContent($xml) //A valid XML
->submit();
```

**Comment by krizzdev** [comment]
Hi @mirkos93 
I haven't used the _POST_PRODUCT_DATA_ type yet. But you're right. We haven't added MWSAuthToken to our QueryString as a parameter. It worked for us without. 
Do you need to add the mws auth token in the https://mws.amazonservices.com/scratchpad/index.html too ?

I'll try to add it without breaking the current version and come back to you again.

**Comment by krizzdev** [comment]
Added MWSAuthToken to request params now in 0.1.10.
Can you update and check if it works?

Don't forget to add 'mws_auth_token' => env('MWS_AUTH_TOKEN'), to your amazon-mws.php if you've published it to your project.

**Comment by mirkos93** [comment]
@krizzdev It worked perfectly. Thanks so much
